#Etape2 : Utiliser une image de base légère pour l'éxécution
FROM node:20-alpine 
WORKDIR /app
COPY package.json package-lock.json ./
RUN npm install --production
COPY . .
EXPOSE 5000
CMD [ "node", "index.js" ]