# Étape 1: Utiliser l'image de base Node.js
FROM node:20

# Définir le répertoire de travail dans le conteneur
WORKDIR /app

# Copier les fichiers package.json et package-lock.json
# (Cela permet de réduire les étapes de re-construction de dépendances si le package.json n'a pas changé)
COPY package.json package-lock.json ./

# Installer les dépendances
RUN npm install

# Copier tout le code source dans le conteneur
COPY . .

# Exposer le port 5000 pour accéder à l'API
EXPOSE 5000

# Démarrer l'application avec Node.js
CMD ["node", "index.js"]